version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-doh
    restart: unless-stopped
    command: proxy-dns --address 0.0.0.0 --port 5353 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query
    networks:
      dns_network:
        ipv4_address: 172.20.0.2
    ports:
      - "5353:5353/udp"
    healthcheck:
      test: ["CMD", "nslookup", "cloudflare.com", "127.0.0.1:5353"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  unbound:
    image: mvance/unbound:latest
    container_name: unbound-resolver
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      - unbound_data:/opt/unbound/etc/unbound/var
    networks:
      dns_network:
        ipv4_address: 172.20.0.3
    depends_on:
      cloudflared:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "drill", "@127.0.0.1", "cloudflare.com"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  dns_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  unbound_data:
    driver: local
